name: Auto Recharge Check
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  recharge:
    runs-on: ubuntu-latest
    steps:
      - name: Call Recharge API
        run: curl -X POST https://yourdomain.com/api/recharge
